import { v } from "convex/values";

export const appRoleValidator = v.union(
  v.literal("admin"),
  v.literal("moderator"),
  v.literal("user"),
  v.literal("creator"),
  v.literal("subscriber"),
);

/** Matches `users` table documents returned from `ctx.db.get`. */
export const userDocValidator = v.object({
  _id: v.id("users"),
  _creationTime: v.number(),
  name: v.optional(v.string()),
  image: v.optional(v.string()),
  email: v.optional(v.string()),
  emailVerificationTime: v.optional(v.number()),
  phone: v.optional(v.string()),
  phoneVerificationTime: v.optional(v.number()),
  isAnonymous: v.optional(v.boolean()),
  legacyId: v.optional(v.string()),
  externalAuthId: v.optional(v.string()),
  fullName: v.optional(v.string()),
  username: v.optional(v.string()),
  discordId: v.optional(v.string()),
  discordUsername: v.optional(v.string()),
  stripeCustomerId: v.optional(v.string()),
  notificationPrefs: v.optional(v.any()),
  createdAt: v.optional(v.number()),
  updatedAt: v.optional(v.number()),
});

export const userWithRolesValidator = v.object({
  _id: v.id("users"),
  _creationTime: v.number(),
  name: v.optional(v.string()),
  image: v.optional(v.string()),
  email: v.optional(v.string()),
  emailVerificationTime: v.optional(v.number()),
  phone: v.optional(v.string()),
  phoneVerificationTime: v.optional(v.number()),
  isAnonymous: v.optional(v.boolean()),
  legacyId: v.optional(v.string()),
  externalAuthId: v.optional(v.string()),
  fullName: v.optional(v.string()),
  username: v.optional(v.string()),
  discordId: v.optional(v.string()),
  discordUsername: v.optional(v.string()),
  stripeCustomerId: v.optional(v.string()),
  notificationPrefs: v.optional(v.any()),
  createdAt: v.optional(v.number()),
  updatedAt: v.optional(v.number()),
  roles: v.array(appRoleValidator),
});

export const subscriptionDocValidator = v.object({
  _id: v.id("subscriptions"),
  _creationTime: v.number(),
  legacyId: v.optional(v.string()),
  userId: v.id("users"),
  creatorId: v.id("creators"),
  productId: v.optional(v.id("products")),
  stripeSubscriptionId: v.optional(v.string()),
  status: v.string(),
  billingStatus: v.optional(v.string()),
  currentPeriodEnd: v.optional(v.number()),
  cancelAtPeriodEnd: v.optional(v.boolean()),
  amountCents: v.number(),
  platformFeeCents: v.number(),
  creatorEarningsCents: v.number(),
  feePercentage: v.number(),
  createdAt: v.number(),
  updatedAt: v.number(),
});

export const subscriptionWithCreatorValidator = v.object({
  _id: v.id("subscriptions"),
  _creationTime: v.number(),
  legacyId: v.optional(v.string()),
  userId: v.id("users"),
  creatorId: v.id("creators"),
  productId: v.optional(v.id("products")),
  stripeSubscriptionId: v.optional(v.string()),
  status: v.string(),
  billingStatus: v.optional(v.string()),
  currentPeriodEnd: v.optional(v.number()),
  cancelAtPeriodEnd: v.optional(v.boolean()),
  amountCents: v.number(),
  platformFeeCents: v.number(),
  creatorEarningsCents: v.number(),
  feePercentage: v.number(),
  createdAt: v.number(),
  updatedAt: v.number(),
  creator: v.object({
    _id: v.id("creators"),
    username: v.string(),
    displayName: v.optional(v.string()),
    avatarUrl: v.optional(v.string()),
    monthlyPriceCents: v.optional(v.number()),
    messagingEnabled: v.boolean(),
  }),
});

export const subscriptionWithUserValidator = v.object({
  _id: v.id("subscriptions"),
  _creationTime: v.number(),
  legacyId: v.optional(v.string()),
  userId: v.id("users"),
  creatorId: v.id("creators"),
  productId: v.optional(v.id("products")),
  stripeSubscriptionId: v.optional(v.string()),
  status: v.string(),
  billingStatus: v.optional(v.string()),
  currentPeriodEnd: v.optional(v.number()),
  cancelAtPeriodEnd: v.optional(v.boolean()),
  amountCents: v.number(),
  platformFeeCents: v.number(),
  creatorEarningsCents: v.number(),
  feePercentage: v.number(),
  createdAt: v.number(),
  updatedAt: v.number(),
  user: v.union(
    v.object({
      _id: v.id("users"),
      email: v.optional(v.string()),
      fullName: v.optional(v.string()),
      username: v.optional(v.string()),
    }),
    v.null(),
  ),
});

export const directMessageDocValidator = v.object({
  _id: v.id("directMessages"),
  _creationTime: v.number(),
  legacyId: v.optional(v.string()),
  creatorId: v.id("creators"),
  subscriberId: v.id("users"),
  senderRole: v.string(),
  body: v.string(),
  read: v.boolean(),
  createdAt: v.number(),
});
